#!/usr/bin/env bash

# Check if homebrew installed
if command -v brew >/dev/null 2>&1; then
    echo ""
else
    echo "Homebrew is not installed. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "Installing packages now..."

brew bundle install

echo "Symlinking dotfiles..."
mkdir -p ~/.config
ln -sf $PWD/nvim $HOME/.config/
ln -sf $PWD/fish $HOME/.config/ 
ln -sf $PWD/zellij $HOME/.config/ 

# sudo chsh -s $(which fish)
